#ifndef PLSQLDELIMETERS
#define PLSQLDELIMETERS

#include <config.h>
#include <unordered_map>

enum class Delimiter: int {
  ADDITION_OPERATOR,
  ASSIGNMENT_OPERATOR,
  ASSOCIATION_OPERATOR,
  ATTRIBUTE_INDICATOR,
  CHARACTER_STRING_DELIMITER,
  COMPONENT_INDICATOR,
  CONCATENATION_OPERATOR,
  DIVISION_OPERATOR,
  EXPONENTIATION_OPERATOR,
  EXPRESSION_OR_LIST_DELIMITER_BEGIN,
  EXPRESSION_OR_LIST_DELIMITER_END,
  HOST_VARIABLE_INDICATOR,
  ITEM_SEPARATOR,
  LABEL_DELIMITER_BEGIN,
  LABEL_DELIMITER_END,
  MULTILINE_COMMENT_DELIMITER_BEGIN,
  MULTILINE_COMMENT_DELIMITER_END,
  MULTIPLICATION_OPERATOR,
  QUOTED_IDENTIFIER_DELIMITER,
  RANGE_OPERATOR,
  RELATIONAL_OPERATOR_EQUAL,
  RELATIONAL_OPERATOR_NOT_EQUAL,
  RELATIONAL_OPERATOR_LESS_THAN,
  RELATIONAL_OPERATOR_GREATER_THAN,
  RELATIONAL_OPERATOR_LESS_THAN_OR_EQUAL,
  RELATIONAL_OPERATOR_GREATER_THAN_OR_EQUAL,
  REMOTE_ACCESS_INDICATOR,
  SINGLELINE_COMMENT_INDICATOR,
  STATEMENT_TERMINATOR,
  SUBTRACTION_OR_NEGATION_OPERATOR
};

extern const std::unordered_map<string,Delimiter> DELEMITER_NAMES;
extern const std::unordered_map<character,bool> DELEMITER_FIRST_PARTS;

#endif // PLSQLDELIMETERS

